apiVersion: 1

datasources:
  - name: GMS Prometheus
    uid: gms-prometheus
    type: prometheus
    access: proxy
    url: $GMS_PROMETHEUS_URL
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 15s
